# backend/ingest/config.py
from pathlib import Path
from config.settings import (
    DATA_DIR,
    STORAGE_DIR,
    EMBEDDING_MODEL_NAME,
    CHUNK_SIZE,
    CHUNK_OVERLAP,
)

BASE_DATA_DIR = DATA_DIR
BASE_STORAGE_DIR = STORAGE_DIR

EMBEDDING_MODEL = EMBEDDING_MODEL_NAME
DEFAULT_CHUNK_SIZE = CHUNK_SIZE
DEFAULT_CHUNK_OVERLAP = CHUNK_OVERLAP
